name: app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+13

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  dio: 5.4.3+1
  mockito:
  cached_network_image: 3.3.0
  logger: 1.3.0
  flutter_spinkit: 5.1.0
  easy_mask: 2.0.1
  flutter_holo_date_picker: 1.1.3
  font_awesome_flutter: 10.3.0
  video_player: 2.8.1
  chewie: 1.7.0
  miniplayer: 1.0.1
  freezed_annotation: 2.2.0
  audio_video_progress_bar: 1.0.0
  line_icons: 2.0.1
  rxdart:
  intl: ^0.18.0
  crop: 0.5.4
  file_picker:
  image_picker: 0.8.6+4
  flutter_image_compress: 1.1.3
  flutter_secure_storage: 8.0.0
  flutter_modular: 6.3.4
  mobx: 2.2.0
  flutter_mobx: 2.0.6+5
  rx_notifier: 2.2.2
  package_info_plus:
  brasil_fields: 1.12.0
  shimmer: 2.0.0
  sliding_up_panel: ^2.0.0+1
  flutter_launcher_icons: 0.13.1
  back_button_interceptor: 7.0.0
  stop_watch_timer: 3.0.2
  flutter_svg: 2.0.9
  video_thumbnail: 0.5.3
  path_provider: 2.1.1
  firebase_crashlytics: 3.4.8
  firebase_core: 2.24.2
  app_links: 5.0.0
  super_sliver_list: 0.4.1
  url_launcher: 6.2.6
  firebase_dynamic_links: ^5.4.8
  sentry_flutter: 8.1.0
  toastification: 2.0.0
  in_app_purchase: 3.2.0
  flutter_inappwebview: 6.0.0
  email_validator: 2.1.17
#  upgrader: 10.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  freezed: 2.3.2
  mobx_codegen: 2.3.0
  build_runner: 2.3.3
  json_serializable: 6.6.1
  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/images/icon/
    - assets/images/icon/svg/
    - assets/images/foods/
    - assets/images/foods/category/
    - assets/images/welcome/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter/static/Inter-ExtraBold.ttf
        - asset: assets/fonts/Inter/static/Inter-Bold.ttf
        - asset: assets/fonts/Inter/static/Inter-SemiBold.ttf
        - asset: assets/fonts/Inter/static/Inter-Regular.ttf
        - asset: assets/fonts/Inter/static/Inter-Medium.ttf
        - asset: assets/fonts/Inter/static/Inter-Light.ttf


flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo-icon.png"
  min_sdk_android: 19
  macos:
    generate: true
    image_path: "assets/logo-icon.png"


flutter_intl:
  enabled: true # Obrigatório. Deve ser definido como verdadeiro para ativar o pacote. Padrão: falso
  main_locale: pt # Opcional. Define o local principal usado para gerar arquivos de localização. O valor fornecido deve consistir em código de idioma e script opcional e códigos de país separados por sublinhado (por exemplo, 'en', 'en_GB', 'zh_Hans', 'zh_Hans_CN'). Padrão: en
