// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPBal7CBgssEs6aYRvB3zEvQRdPv1HDqQ',
    appId: '1:220683252898:android:1d6ccb0bec66a74bdb93fb',
    messagingSenderId: '220683252898',
    projectId: 'ibetter',
    storageBucket: 'ibetter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmKYglTErj6t_OpyWLA3J3Gkgj5rxaBZU',
    appId: '1:220683252898:ios:e5a35a416df33839db93fb',
    messagingSenderId: '220683252898',
    projectId: 'ibetter',
    storageBucket: 'ibetter.appspot.com',
    iosBundleId: 'com.ibetter.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCmKYglTErj6t_OpyWLA3J3Gkgj5rxaBZU',
    appId: '1:220683252898:ios:f85502f9fffc24d1db93fb',
    messagingSenderId: '220683252898',
    projectId: 'ibetter',
    storageBucket: 'ibetter.appspot.com',
    iosBundleId: 'com.ibetter.appBase',
  );
}